mode: deployment
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "localhost:4317"
        http:
          endpoint: "localhost:4318"
  exporters:
#    loadbalancing:
#      protocol:
#        otlp:
#          headers:
#            api-key: ""
#          tls:
#            insecure: true
#      resolver:
#        static:
#          hostnames:
#            - https://otlp.nr-data.net:4317
    otlp/newrelic:
      endpoint: "https://otlp.nr-data.net:4317"
      headers:
        api-key: ""
    debug:
      verbosity: detailed
      sampling_initial: 5
      sampling_thereafter: 200
    logging:
      verbosity: detailed
  service:
    telemetry:
      logs:
        level: debug
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp/newrelic, debug, logging]
      metrics:
        receivers: [otlp]
        exporters: [otlp/newrelic, debug, logging]
      logs:
        receivers: [otlp]
        exporters: [otlp/newrelic, debug, logging]

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 256Mi
    cpu: "0.2"