apiVersion: v1 
kind: ConfigMap
metadata:
  name: otel-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otelcol'
              scrape_interval: 10s
              static_configs:
              - targets: ['0.0.0.0:8888']

    processors:
      resource:
        attributes:
          - key: host.id
            from_attribute: host.name
            action: upsert
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources: 
            - from: resource_attribute
              name: k8s.pod.uid
      batch:

    exporters:
      otlp:
        endpoint: "https://otlp.nr-data.net:4318"
        headers:
          api-key: {{ .Values.newRelic.apiKey }}

    extensions:
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: ":8888"
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [resource, k8sattributes, batch]
          exporters: [otlp]