apiVersion: v1 
kind: ConfigMap
metadata:
  name: {{ include "otel-agent-chart.name" . }}-config
data:
  otel-collector-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kube-state-metrics'
              static_configs:
                - targets: ['kube-state-metrics-service:8080']

    processors:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8888"
      # the newrelic exporter is deprecated in favor of the OTLP exporter 
      # newrelic:
      #   api_key: {{ .Values.newRelic.apiKey }}
      otlp:
        endpoint: "https://otlp.nr-data.net:4317"
        headers:
          api-key: {{ .Values.newRelic.apiKey }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [otlp, prometheus]

