apiVersion: v1 
kind: ConfigMap
metadata:
  name: {{ include "otel-agent-chart.name" . }}-config
data:
  otel-collector-config.yaml: |
    {{ .Files.Get "config/otel-colletor-config.yaml" | nindent 8 }}