apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "otel-agent-chart.fullname" . }}
  namespace: {{ .Values.newRelic.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
    helm.sh/chart: {{ include "otel-agent-chart.chart" . }}
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/daemonset-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: otel-service-account
      containers: 
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          command:
            - /otelcol-contrib
            - --config=/conf/otel-collector-config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HOST_IP
              valueFrom: 
                fieldRef:
                  fieldPath: status.hostIP 
            - name: OTEL_EXPORTER_OTLP_ENDPOINT 
              value: "http://$(HOST_IP):55680"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.uid
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.instance.id=$(POD_NAME),k8s.pod.uid=$(POD_UID)
          volumeMounts:
            - name: config-volume
              mountPath: /conf
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: otel-config
        - name: varlogpods 
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}