apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-agent-chart.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: opentelemetry
    component: gateway-collector
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: opentelemetry
      component: gateway-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: gateway-collector
    spec:
      serviceAccountName: {{ include "otel-agent-chart.fullname" . }}
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest # specify image
          args: ["--config", "/config/deployment-config.yaml"]
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - containerPort: 4317   # otlp grpc
            - containerPort: 4318   # otlp http
          volumeMounts:
            - name: deployment-config
              mountPath: /config
      volumes:
        - name: deployment-config
          configMap:
            name: {{ include "otel-agent-chart.fullname" . }}-deployment-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}