apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-deployment-config
  namespace: {{ Values.newRelic.namespace }}
data:
  deployment-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      k8s_events:
    #    namespaces: [default]
    processors:
      batch:
      resource:
        attributes:
          - key: "event.name"
            action: upsert
            value: "InfrastructureEvent"
          - key: "event.domain"
            action: upsert
            value: "newrelic-otel-event"
          - key: "category"
            action: upsert
            value: "kubernetes"
          - key: k8s.cluster.name
            action: upsert
            value: {{ .Values.cluster.name }}
          - key: newrelicOnly
            action: upsert
            value: 'true'
    exporters:
      otlp:
        endpoint: "otel-gateway:4317"
        tls:
          insecure: true
      otlphttp/newrelic:
        endpoint: {{ .Values.newRelic.endpoint }}
        headers:
          api-key: {{ .Values.newRelic.apiKey }}
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        # Uncomment below if exporting traces to NR
        # traces:
        #   receivers: [otlp]
        #   processors: [batch]
        #   exporters: [otlphttp/newrelic, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/newrelic, debug]
        logs/events:
          receivers: [k8s_events]
          processors: [resource, batch]
          exporters: [otlp, debug]