apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-events-config
data:
  events-config.yaml: |
    receivers:
      k8s_events:
    #    namespaces: [default]
    processors:
      resource:
        attributes:
          - key: "event.name"
            action: upsert
            value: "InfrastructureEvent"
          - key: "event.domain"
            action: upsert
            value: "newrelic-otel-event"
          - key: "category"
            action: upsert
            value: "kubernetes"
          - key: k8s.cluster.name
            action: upsert
            value: {{ .Values.cluster.name }}
    exporters:
      otlp:
        endpoint: "otel-gateway:4317"
        tls:
          insecure: true
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
    service:
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: localhost:9999
      pipelines:
        logs:
          receivers: [k8s_events]
          processors: [resource]
          exporters: [otlp, debug]