apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-events-config
data:
  config.yaml: |
    receivers:
      k8s_events:
    #    namespaces: [default]
    exporters:
      otlp:
        endpoint: {{ .Values.newRelic.endpoint }}
        headers:
          api-key: {{ .Values.newRelic.apiKey }}
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200

    processors:
      resource:
        attributes:
          - key: "event.name"
            action: upsert
            value: "InfrastructureEvent"
          - key: "event.domain"
            action: upsert
            value: "newrelic-otel-event"
          - key: "category"
            action: upsert
            value: "kubernetes"
          - key: k8s.cluster.name
            action: upsert
            value: {{ .Values.cluster.name }}
          - key: newrelicOnly
            action: upsert
            value: 'true'
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        logs:
          receivers: [k8s_events]
          processors: [resource]
          exporters: [otlp, debug]