apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-gateway-config
data:
  otel-gateway-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318

    processors:
      batch:

    exporters:
      otlp/newrelic:
        endpoint: {{ .Values.newRelic.endpoint }}
        headers:
          api-key: {{ .Values.newRelic.apiKey }}
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      logging:
        verbosity: detailed

    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/newrelic, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/newrelic, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/newrelic, debug]