apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-gateway
  labels:
    app: opentelemetry
    component: otel-gateway
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-gateway
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      namespace: opentelemetry
      labels:
        app: opentelemetry
        component: otel-gateway
    spec:
      containers:
        - command:
            - '/otelcol'
            - '--config=/conf/otel-gateway-config.yaml'
          image: otel/opentelemetry-collector:latest
          name: otel-collector
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 4317   # otlp grpc
            - containerPort: 4318   # otlp http
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - name: otel-gateway-config-vol
              mountPath: /conf
      volumes:
        - name: otel-gateway-config-vol
          configMap:
            name: otel-gateway-config
{{/*            items:*/}}
{{/*              - key: otel-collector-config*/}}
{{/*                path: otel-collector-config.yaml*/}}
