apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "otel-agent-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
    helm.sh/chart: {{ include "otel-agent-chart.chart" . }}
spec: 
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "otel-agent-chart.name" . }}
    spec:
      containers: 
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            # httpGet:
            #   path: /healthz
            #   port: 8080
            # initialDelaySeconds: 10 
            # periodSeconds: 20 
          readinessProbe:
            # httpGet:
            #   path: /healthz
            #   port: 8080
            # initialDelaySeconds: 10 
            # periodSeconds: 20 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "otel-agent-chart.name" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}