apiVersion: v1
kind: Service
metadata:
  name: otel-gateway
  namespace: {{ .Values.newRelic.namespace }}
  labels:
    app: opentelemetry
    component: otel-gateway
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    component: gateway-collector
  internalTrafficPolicy: Cluster