apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-agent-chart.fullname" . }}
  labels:
    {{- include "otel-agent-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "otel-agent-chart.selectorLabels" . | nindent 4 }}
