apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nr-k8s-otel-collector.fullname" . }}
  labels:
    {{- include "nr-k8s-otel-collector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nr-k8s-otel-collector.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nr-k8s-otel-collector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
