apiVersion: v1 
kind: ServiceAccount
metadata:
  name: {{ include "nr-k8s-otel-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nr-k8s-otel-collector.labels" . | nindent 4 }}
